# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='api_user.API_USER'),
        ),
    ]
