# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160305_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_point',
            field=models.CharField(default='xx', max_length=200),
        ),
    ]
