# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_end_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_point',
        ),
    ]
