# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='service',
            new_name='endpoint',
        ),
    ]
