# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 08:32
from __future__ import unicode_literals

import developer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_org_name', models.CharField(max_length=200)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.FileField(upload_to=developer.models.generate_filename)),
            ],
        ),
    ]
