# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='api_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='api_user',
            name='username',
        ),
        migrations.AddField(
            model_name='api_user',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='api_user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Organization'), (3, 'Developer')], default=3, max_length=1),
        ),
    ]
